# -*- coding: utf-8 -*-
"""CV_alloy_TC3/22/2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L8MZxA0G5zNOCKJ-eNUXAt8FGfOZOV6N
"""

from xgboost import XGBRegressor
import pandas as pd
import numpy as np
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import cross_val_score

df = pd.read_csv('/content/NEW_TC_UP.csv')

# Separate the target variable from the features
X = df.drop("TC", axis=1)
y = df["TC"]

XGB=XGBRegressor(colsample_bytree =0.4, n_estimators=900, learning_rate=0.1, max_depth=6, gamma=0,subsample= 0.5)
cv = RepeatedKFold(n_splits=10, random_state=1)
np.mean(cross_val_score(XGB, X, y, cv=cv))





